name: "Purge Cache Cloudflare Zone"
description: "Purge a zone's cache via the Cloudflare API"
author: "Jonakemon"
branding:
  color: "blue"
  icon: "trash-2"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.cloudflareZone }}
    - ${{ inputs.cloudflareApiKey }}
    - ${{ inputs.purgeURLs }}
